import express from 'express';
import * as studentController from '../controllers/student.controller.js';
import { requirePermission } from '../middleware/permission.middleware.js';
import { authenticate } from '../middleware/auth.middleware.js';
import { validateStudent } from '../middleware/student.validation.js';
const router = express.Router();
router.get('/', authenticate, requirePermission("student:read"), studentController.getALLStudents);
router.get('/:id', authenticate, requirePermission("student:read"), studentController.getStudentById);
router.post('/', authenticate, requirePermission("student:create"), validateStudent, studentController.createStudent);
router.patch('/:id', authenticate, requirePermission("student:update"), validateStudent, studentController.updateStudent);
router.delete('/:id', authenticate, requirePermission("student:delete"), studentController.deleteStudent);
export default router;
